2022-01-23 19:02:59: Error undefined: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:267:15)
    at ServerResponse.send (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:158:21)
    at checkAuthToken (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\authorization\checkAuthToken.ts:19:25)
    at Layer.handle [as handle_request] (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\index.js:284:7
2022-01-23 19:03:12: Error undefined: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:267:15)
    at ServerResponse.send (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:158:21)
    at checkAuthToken (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\authorization\checkAuthToken.ts:19:25)
    at Layer.handle [as handle_request] (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\index.js:284:7
2022-01-23 19:03:31: Error undefined: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:267:15)
    at ServerResponse.send (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:158:21)
    at checkAuthToken (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\authorization\checkAuthToken.ts:19:25)
    at Layer.handle [as handle_request] (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\index.js:284:7
2022-01-23 19:03:31: Error undefined: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:267:15)
    at ServerResponse.send (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:158:21)
    at checkAuthToken (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\authorization\checkAuthToken.ts:19:25)
    at Layer.handle [as handle_request] (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\index.js:284:7
2022-01-23 19:03:31: Error undefined: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:267:15)
    at ServerResponse.send (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\response.js:158:21)
    at checkAuthToken (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\authorization\checkAuthToken.ts:19:25)
    at Layer.handle [as handle_request] (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\index.js:284:7
2022-01-23 19:03:31: CustomError 404: The task with id 2ba1f337-7ddc-4e9a-a97c-f8f2e70b7257 was not found
CustomError: The task with id 2ba1f337-7ddc-4e9a-a97c-f8f2e70b7257 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:27:25
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-23 19:03:31: CustomError 404: The board with id 63e48348-7ad4-4534-ad05-c0b1f58003f4 was not found
CustomError: The board with id 63e48348-7ad4-4534-ad05-c0b1f58003f4 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.memory.repository.ts:26:26
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.memory.repository.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-23 19:03:31: CustomError 404: The task with id 2e43cc7e-831e-4f63-b3fd-1dfac6ccfca0 was not found
CustomError: The task with id 2e43cc7e-831e-4f63-b3fd-1dfac6ccfca0 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:27:25
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-23 19:03:31: CustomError 404: The task with id 64b38127-9c8d-46a7-aa3a-424a0e855d7a was not found
CustomError: The task with id 64b38127-9c8d-46a7-aa3a-424a0e855d7a was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:27:25
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-23 19:03:31: CustomError 404: The task with id ac21e4d6-88d2-459c-8290-4cf82cb68f13 was not found
CustomError: The task with id ac21e4d6-88d2-459c-8290-4cf82cb68f13 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:27:25
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-23 19:03:31: CustomError 404: The task with id fb513198-380f-48b6-af16-af6170a06c0f was not found
CustomError: The task with id fb513198-380f-48b6-af16-af6170a06c0f was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:27:25
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-23 19:03:31: CustomError 404: The task with id b6d546da-7db8-4690-9635-0de86c5ae9e2 was not found
CustomError: The task with id b6d546da-7db8-4690-9635-0de86c5ae9e2 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:27:25
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
